### ISSUE TITLE
How to launch?

### ISSUE THREAD

**Issue by nicocoh** [Creeperman007/SEContestCommands#3]
Hello,
I'm sorry but I don't know how to contact you by an other way.

I would love to use your code to start some contests from twitch chat using streamelements but I don't know what I have to do to launch your code?

Could you please tell me how to do?
Thank you,

**Comment by fajnyCreeper** [comment]
Hey,
so, first of all, you would need some kind of web hosting because this runs using PHP

Then you would need to install [Composer](https://getcomposer.org/) which is dependency manager for PHP

When you install Composer, download this repository, extract it (somewhere). open command line, switch to the extracted repository and write `composer install` which will install all needed dependencies.

After the composer installed all needed files, you will need to create file called `credentials.php` in which, you will put following content
```PHP
<?php
$key = "random string";
$bearer = "SE JWT token";
```
Important thing is to change those two variables - variable `$key` is all up to you, so you can put there random characters. Variable `$bearer` is your JWT token from StreamElements which you can find [here](https://streamelements.com/dashboard/account/channels) (after clicking "Show secrets")

Save the file.

This is all the steps, you need to do, to correctly setup the app. Next thing is uploading your project to you WWW hosting to destination of your own.

When you are done with upload, now you need to go to StreamElements dashboard, and create new command (name doesn't matter, but `!bets` is preferred) and into the response you put this (with edited path to your application)
`${customapi.example.com/main.php?key=my_key&args=${pathescape ${queryescape ${1:|' '}}}}`

One important thing is to change the key variable (now replaced with `my_key`) to the correct string, you put into `credentials.php` as this is to recognize your request and to be sure, the contests are not randomly opened.

Next thing to do, which is highly recommended is going to "Advanced settings" of the command and check "Hide command from public pages"

Now you just adjust the minimal user level (which can control contests) to your liking, save the command, and you should be ready to use them in chat using [these commands](https://github.com/Creeperman007/SEContestCommands#chat-commands)

**Comment by nicocoh** [comment]
Hello, thanks a lot for our answer.

Should I need to launch Composer each time I start my computer to be able to use the chat commands or I just need to do the process one time?

**Comment by fajnyCreeper** [comment]
You need to do the process only once

**Comment by nicocoh** [comment]
ok great thanks for your answer.

Is it working if I have a web hosting provider for my website like this one to send all my files ?
https://www.o2switch.fr/

**Comment by fajnyCreeper** [comment]
Yes, you just upload all the files from the repository to your hosting using FTP and you are ready to go.

**Comment by nicocoh** [comment]
ok thank you.

I think I do all you asked but I'm not sure...so because I'm a very big noob, could you confirm I did all you said?

**Comment by fajnyCreeper** [comment]
Looks alright, but just to confirm, is there folder called `vendor` in the directory?

Your directory should look like this 
![image](https://user-images.githubusercontent.com/13434551/95873180-f18cce80-0d6f-11eb-8bc3-0131d08ba518.png)

**Comment by nicocoh** [comment]
yes, I have a vendor directory, too.

So, now I have to send all of these files you show me in your last screen to a new folder in my hosting, right?

**Comment by fajnyCreeper** [comment]
Yes, now you upload all your files to your webhosting

**Comment by nicocoh** [comment]
Did it,

this is what I obtain in twitch :/

![Capture d’écran 2020-10-13 163629](https://user-images.githubusercontent.com/72791243/95875437-4e898400-0d72-11eb-9ae7-b7ef7a2a9dcf.png)

**Comment by fajnyCreeper** [comment]
In the command, that you add to StreamElements, you need to change the response so that from
`${customapi.example.com/main.php?key=my_key&args=${pathescape ${queryescape ${1:|' '}}}}`
you get 
`${customapi.yourdomain.com/pathtotherepository/main.php?key=my_key&args=${pathescape ${queryescape ${1:|' '}}}}`

**Comment by fajnyCreeper** [comment]
And the second thing is, you don't put arguments into the <> brackets.

**Comment by nicocoh** [comment]
it works!!! you are the boss! It's so cool thank you so much.

**Comment by fajnyCreeper** [comment]
Glad it works 😄
